### ISSUE TITLE
bower.json should exclude test and demo data.

### ISSUE THREAD

**Issue by nik3daz** [Polymer/core-list#59]
The core-list package is currently blowing out my packaged app size because the demos/ data is 18 mb. There should be an ignore: [ "demos/" ] line in bower.json so bower clients don't pull in the demo data.

Also consider ignoring test/ and images/.

**Comment by kevinpschaaf** [comment]
> There should be an ignore: [ "demos/" ] line in bower.json 

We had exactly this at one point (https://github.com/Polymer/core-list/commit/cd7192e9153e1ec27ab3efd9f5f08c0164b2147d), but as @IntranetFactory mentioned, we've gone around around a few times on this (ref https://github.com/Polymer/core-list/issues/32) and what we have now (demos included in bower package, but demo dependencies must be explicitly bower installed) is where we landed.

I went ahead and removed three pretty huge data files used during development/testing that weren't being used for the demos checked in, which reduces ~13mb of the bulk: https://github.com/Polymer/core-list/commit/1ce0b623481fbc0fba305efa5e3f7f9d8c4c322a.  Not a general solution, but should lessen the problem

Closing, as there's no immediate plan to change the contents of bower packages.  Since most production environment/packaging build step should generally involve vulcanize/concatenation/minifying/etc., that would be the right time to exclude any non-production files from the package (not just demo files; you shouldn't be including the unconcatenated source files either, for example).
